/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Demon.gltf -o src/components/Demon.jsx -r public 
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Demon(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/models/Demon.gltf");
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		actions["Idle"].reset().fadeIn(0.5).play();
		return () => actions["Idle"].fadeOut(0.5);
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Scene">
				<group name="CharacterArmature">
					<primitive object={nodes.Root} />
					<skinnedMesh
						name="Demon"
						geometry={nodes.Demon.geometry}
						material={materials.Atlas}
						skeleton={nodes.Demon.skeleton}
					/>
					<skinnedMesh
						name="Trident"
						geometry={nodes.Trident.geometry}
						material={materials.Atlas}
						skeleton={nodes.Trident.skeleton}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/models/Demon.gltf");
